name = "keyteo"
description = "CV with Keyteo branding and logo"
main_file = "main.typ"
dependencies = ["template.typ"]
features = ["header_logo", "branded_footer"]
languages = ["en", "fr"]
version = "1.0.0"
