# Personal Information
name = "salma-bennekrouf"
phonenumber = "54354"
email = ""
address = ""
picture = "profile.png"

# Job title
job_title = "Technical Lead"

# Manager information
manager_name = "Anthony Levavasseur"
manager_email = "alevavasseur@keyteo.ch"
manager_phone = "078 230 36 38"

# Consultant information  
consultant_name = "salma-bennekrouf"

# Manager information
manager_info = "Anthony Levavasseur – alevavasseur@keyteo.ch – 078 230 36 38"

# Company/Logo information (for logo template)
company_name = ""
company_logo = "logo.png"

[links]
github = ""
linkedin = ""
personal = ""

# Technical Skills
[skills]
Languages = [""]
Frameworks = [""]
Others = [""]

# Education & Certifications
[[education]]
title = ""
date = ""

# Languages
[languages]
native = [""]
fluent = [""]
intermediate = [""]
basic = [""]
